// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	kitex_gen "github.com/doutokk/doutok/app/product/biz/router/kitex_gen"
	product "github.com/doutokk/doutok/app/product/biz/router/product"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	kitex_gen.Register(r)

	product.Register(r)
}
