// Code generated by hertz generator.

package user

import (
	"context"
	"github.com/doutokk/doutok/app/user/biz/service"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	user "github.com/doutokk/doutok/rpc_gen/kitex_gen/user"
)

// Register .
// @router /register [POST]
func Register(ctx context.Context, c *app.RequestContext) {
	var err error
	var req user.RegisterReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	s := service.NewRegisterService(ctx)
	resp, err := s.Run(&req)

	c.JSON(consts.StatusOK, resp)
}

// Login .
// @router /login [POST]
func Login(ctx context.Context, c *app.RequestContext) {
	var err error
	var req user.LoginReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	s := service.NewLoginService(ctx)
	resp, err := s.Run(&req)
	c.JSON(consts.StatusOK, resp)
}
