// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	auth "douyin-commerce/biz/router/auth"
	payment "douyin-commerce/biz/router/payment"
	"github.com/cloudwego/hertz/pkg/app/server"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	payment.Register(r)

	auth.Register(r)
}
